# Generated by Django 5.1.1 on 2024-10-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReaction',
        ),
    ]
