# Generated by Django 5.1.1 on 2025-03-04 00:43

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='delivery_boy_pics/')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], default='bike', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_covers/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_delivery_time',
            field=models.PositiveIntegerField(help_text='Maximum delivery time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_delivery_time',
            field=models.PositiveIntegerField(help_text='Minimum delivery time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='opening_hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(default=posts.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
