# Generated by Django 5.1.1 on 2025-03-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_deliveryboy_brand_address_brand_cover_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='name',
        ),
    ]
