# Generated by Django 5.1.1 on 2025-03-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_title_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='title',
        ),
    ]
