# Generated by Django 5.1.1 on 2025-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_name_brand_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories', to='posts.brand'),
        ),
    ]
