# Generated by Django 5.1.1 on 2025-03-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='clothesType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='brand',
            name='campus',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='brand',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='radius',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='posts.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='addons',
            field=models.JSONField(blank=True, help_text="JSON format: {'Water': 5.00, 'Extra Cheese': 2.50}", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='posts.brand'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('walk', 'Walk')], default='bike', max_length=100),
        ),
    ]
