# Generated by Django 5.1.1 on 2025-03-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_addon_campus_remove_product_clothestype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='radius',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
