# Generated by Django 5.1.1 on 2025-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_brand_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
