# Generated by Django 5.1.1 on 2025-03-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_addon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
