# Generated by Django 5.1.1 on 2025-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_brand_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
