# Generated by Django 5.1.1 on 2025-04-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_product_imageurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
