# Generated by Django 5.1.1 on 2025-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_deliveryboy_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
