# Generated by Django 5.1.1 on 2025-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_deliveryboy_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cuisine_types',
            field=models.TextField(default='Asian,Chinese,Indian'),
        ),
    ]
