# Generated by Django 5.1.1 on 2025-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_brand_cuisine_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cuisine_types',
            field=models.TextField(default='Asian, Chinese, Indian'),
        ),
    ]
