# Generated by Django 5.1.1 on 2025-05-08 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_brand_latitude_brand_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.deliveryboy')),
            ],
        ),
    ]
