# Generated by Django 5.1.1 on 2025-05-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_brand_cuisine_types'),
        ('posts', '0016_alter_deliveryboy_user'),
    ]

    operations = [
    ]
