# Generated by Django 5.1.1 on 2025-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_merge_20250513_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
