# Generated by Django 5.1.1 on 2025-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_brand_radius_alter_brand_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories', to='posts.brand'),
        ),
    ]
