# Generated by Django 5.1.1 on 2025-05-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_category_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagePublicIds',
            field=models.JSONField(default=list),
        ),
    ]
