# Generated by Django 5.1.1 on 2025-05-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_brand_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='campus',
        ),
    ]
