# Generated by Django 5.1.1 on 2025-05-28 01:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_remove_brand_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='nrc_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='nrc_pics'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='nrc_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='nrc_pics'),
        ),
    ]
