# Generated by Django 5.1.1 on 2025-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_deliveryboy_nrc_back_deliveryboy_nrc_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
