# Generated by Django 5.1.1 on 2025-05-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_deliveryboy_nrc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cuisine_types',
            field=models.TextField(blank=True),
        ),
    ]
