# Generated by Django 5.1.1 on 2025-04-21 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('operator', models.CharField(max_length=50)),
                ('accountName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amountSettled', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('createdAt', models.DateTimeField()),
                ('settledAt', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('accountId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiatedAt', models.DateTimeField()),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bearer', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(max_length=255)),
                ('lencoReference', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('reasonForFailure', models.TextField(blank=True, null=True)),
                ('settlementStatus', models.CharField(max_length=20)),
                ('bankAccountDetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.bankaccountdetails')),
                ('cardDetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.carddetails')),
                ('mobileMoneyDetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.mobilemoneydetails')),
                ('settlement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.settlement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
