# Generated by Django 5.1.1 on 2025-06-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
