# Generated by Django 5.1.1 on 2025-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_address_lat_alter_address_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='surname',
            field=models.CharField(default='Munali', max_length=255),
        ),
    ]
