# Generated by Django 5.1.1 on 2025-05-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_address_surname'),
        ('extras', '0004_remove_address_room_number_alter_address_addresstype'),
    ]

    operations = [
    ]
