# Generated by Django 5.1.1 on 2025-06-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_merge_20250513_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='surname',
        ),
    ]
