# Generated by Django 5.1.1 on 2024-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='Black', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='S', max_length=50),
        ),
    ]
