# Generated by Django 5.1.1 on 2025-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_color_remove_cart_size_cart_addons'),
        ('posts', '0007_alter_brand_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addons',
            field=models.ManyToManyField(blank=True, to='posts.addon'),
        ),
    ]
