# Generated by Django 5.1.1 on 2025-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
