# Generated by Django 5.1.1 on 2025-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room_number',
        ),
    ]
