# Generated by Django 5.1.1 on 2025-05-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_merge_20250513_1930'),
        ('orders', '0004_remove_order_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='earnings',
        ),
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='extras.address'),
        ),
    ]
