# Generated by Django 5.1.1 on 2025-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_earnings_order_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, default='No instructions given'),
        ),
    ]
