# Generated by Django 5.1.1 on 2025-06-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
